# Default Profile
[profile.default]
solc-version = "0.8.22"
optimizer = true
optimizer-runs = 1_000
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'

# Gas reporting
gas_reports = [
  "ContractFactory",
  "Registry",
  "Allo",
  "RFPSimpleStrategy",
  "RFPCommitteeStrategy",
  "QVSimpleStrategy",
  "DonationVotingMerkleDistributionDirectTransferStrategy",
  "DonationVotingMerkleDistributionVaultStrategy",
  "QVImpactStreamStrategy",
  "RecipientSuperApp",
  "SuperAppBaseSQF",
  "SQFSuperFluidStrategy"
]
gas_reports_ignore = [
  "TestStrategy",
  "QVBaseStrategyTestMock",
  "Permit2",
  "MockStrategy",
]

# Storage layout compatibility 
build_info = true
extra_output = ["storageLayout"]
# Grants access to solc
allow_paths = ['node_modules']

[fmt]
ignore = [
  'contracts/strategies/deprecated/_poc/qv-hackathon/SchemaResolver.sol',
  'contracts/strategies/deprecated/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol',
  'test/invariant/fuzz/Setup.t.sol',
	'test/invariant/fuzz/handlers/HandlerAllo.t.sol',
	'test/invariant/fuzz/helpers/Actors.t.sol',
	'test/invariant/fuzz/helpers/FuzzERC20.sol',
	'test/invariant/fuzz/helpers/IStdCheats.sol',
	'test/invariant/fuzz/helpers/Utils.t.sol',
	'test/invariant/fuzz/properties/PropertiesAllo.t.sol',
	'test/invariant/fuzz/properties/PropertiesParent.t.sol'
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
opgoerli = "${OPGOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"